# Generated by Django 4.1.13 on 2024-03-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('kkal', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('photo', models.ImageField(upload_to='pizzas/')),
                ('price', models.IntegerField()),
                ('avaible', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=120)),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(blank=True, max_length=120, null=True)),
                ('pizza_img', models.ImageField(blank=True, max_length=120, null=True, upload_to='')),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pizza.cart')),
                ('pizza', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Pizza.pizza')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
